### ISSUE TITLE
Firefox (at least 26) does not work

### ISSUE THREAD

**Issue by casarock** [dalekjs/dalek-browser-firefox#9]
When I install current dalek-browser-firefox I am not able to run my Test with Firefox 26. Starting tests result in:

```
dalek mytest.js -b firefox
Running tests
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Running Browser: Mozilla Firefox
OS:
```

Browser comes up, but test will not start.

**Comment by Leprosy** [comment]
Same here, Ubuntu 14.04, FF41 using latest packages of dalekjs

**Comment by cjmanning** [comment]
+1 I am experiencing the same issue with Ubuntu 14.04 and FF40 and FF41.

**Comment by craduran** [comment]
+1 I tried to run dalek on chrome and yes, it is working. But when I tried to run using firefox, -_- it stuck on OS:

```
Running tests
Running Browser: Mozilla Firefox
OS: 
```
